(package "diminish-buffer"
         "0.2.0"
         "Diminish (hide) buffers from buffer-menu")

(website-url "https://github.com/jcs-elpa/diminish-buffer")
(keywords "diminish" "hide" "buffer" "menu")

(package-file "diminish-buffer.el")

(source "melpa")

(depends-on "emacs" "24.4")

(setq network-security-level 'low)  ; see https://github.com/jcs090218/setup-emacs-windows/issues/156#issuecomment-932956432
